language: rust

sudo: required

matrix:
  include:
    - language: rust
      rust: 1.42.0
      branches:
        only:
          - master
      addons:
        apt:
          packages:
            - ca-certificates
            - file
            - build-essential
            - autoconf
            - automake
            - autotools-dev
            - libtool
            - xutils-dev
            - cmake
            - pkg-config
            - libfreetype6-dev
            - libfontconfig1-dev
            - xclip
      script:
        - cd $TRAVIS_BUILD_DIR/engine && cargo build --verbose --all && cargo test --verbose --all
    - language: node_js
      node_js: 12.16
      branches:
        only:
          - master
      before_script:
        - cd $TRAVIS_BUILD_DIR/web && npm install
        - cd $TRAVIS_BUILD_DIR/web/react-spa && npm install
        - cd $TRAVIS_BUILD_DIR/web/server && npm install
      script:
        - cd $TRAVIS_BUILD_DIR/web && npm run test